# Generated by Django 5.0.11 on 2026-09-21 12:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZipContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('file', models.CharField(max_length=2048)),
                ('md5sum', models.CharField(blank=True, max_length=32, null=True)),
                ('suffix', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZipArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('archive', models.CharField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FluxFile',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('zipContent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='floppies.zipcontent')),
                ('file', models.CharField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('zipContent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='floppies.zipcontent')),
                ('raw_read', models.TextField()),
                ('converted', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(db_index=True, max_length=500)),
                ('fullArchivePath', models.URLField(blank=True, max_length=600, null=True)),
                ('folder', models.CharField(blank=True, max_length=2048, null=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('publicationDate', models.DateField(blank=True, null=True)),
                ('mediatype', models.CharField(choices=[('TX', 'Texts'), ('ET', 'Etree'), ('AU', 'Audio'), ('MV', 'Movies'), ('SW', 'Software'), ('IM', 'Image'), ('DA', 'Data'), ('WB', 'Web'), ('CO', 'Collection'), ('AC', 'Account')], default='SW', max_length=2)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('hasFluxFile', models.BooleanField(default=False)),
                ('hasFileContents', models.BooleanField(default=False)),
                ('hasDiskImg', models.BooleanField(default=False)),
                ('needsWork', models.BooleanField(default=False)),
                ('readyToUpload', models.BooleanField(default=False)),
                ('doNotUpload', models.BooleanField(default=False)),
                ('archive_sync_status', models.CharField(choices=[('NC', 'Never Checked'), ('IS', 'In Sync'), ('OS', 'Out of Sync'), ('LO', 'Local Only (Not in Archive)'), ('AO', 'Archive Only (Not Local)'), ('ER', 'Sync Error')], default='NC', help_text='Current synchronization status with Internet Archive', max_length=2)),
                ('last_sync_check', models.DateTimeField(blank=True, help_text='Last time sync status was checked against Internet Archive', null=True)),
                ('last_archive_sync', models.DateTimeField(blank=True, help_text='Last time this entry was successfully synchronized with Internet Archive', null=True)),
                ('sync_notes', models.TextField(blank=True, help_text='Details about synchronization differences or issues', null=True)),
                ('collections', models.ManyToManyField(blank=True, to='floppies.archcollection')),
                ('contributors', models.ManyToManyField(blank=True, to='floppies.contributor')),
                ('creators', models.ManyToManyField(blank=True, to='floppies.creator')),
                ('duplicates', models.ManyToManyField(blank=True, help_text='Other entries that are exact duplicates (same MD5 hashes for all files)', to='floppies.entry')),
                ('languages', models.ManyToManyField(blank=True, to='floppies.language')),
                ('subjects', models.ManyToManyField(blank=True, to='floppies.subject')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('image', models.CharField(max_length=2048)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='floppies.entry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RandoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('file', models.CharField(max_length=2048)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randos', to='floppies.entry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScriptRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('runtime', models.DateTimeField(auto_now_add=True)),
                ('parentPath', models.CharField(blank=True, max_length=2048, null=True)),
                ('function', models.CharField(blank=True, max_length=512, null=True)),
                ('script', models.CharField(blank=True, max_length=2048, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppies.entry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='zipcontent',
            name='zipArchive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppies.ziparchive'),
        ),
        migrations.AddField(
            model_name='ziparchive',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziparchives', to='floppies.entry'),
        ),
        migrations.CreateModel(
            name='InfoChunk',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fluxFile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='floppies.fluxfile')),
                ('info_version', models.PositiveSmallIntegerField()),
                ('creator', models.CharField(max_length=32)),
                ('drive_type', models.PositiveSmallIntegerField(choices=[(1, '5.25″ SS 40trk 0.25 step'), (2, '3.5″ DS 80trk Apple CLV'), (3, '5.25″ DS 80trk'), (4, '5.25″ DS 40trk'), (5, '3.5″ DS 80trk'), (6, '8″ DS'), (7, '3″ DS 80trk'), (8, '3″ DS 40trk')])),
                ('write_protected', models.BooleanField()),
                ('synchronized', models.BooleanField()),
                ('hard_sector_count', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaChunk',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fluxFile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='floppies.fluxfile')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('developer', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('it', 'Italian'), ('nl', 'Dutch'), ('pt', 'Portuguese'), ('da', 'Danish'), ('fi', 'Finnish'), ('no', 'Norwegian'), ('sv', 'Swedish'), ('ru', 'Russian'), ('pl', 'Polish'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('th', 'Thai'), ('cs', 'Czech'), ('hu', 'Hungarian'), ('ca', 'Catalan'), ('hr', 'Croatian'), ('el', 'Greek'), ('he', 'Hebrew'), ('ro', 'Romanian'), ('sk', 'Slovak'), ('uk', 'Ukrainian'), ('id', 'Indonesian'), ('ms', 'Malay'), ('vi', 'Vietnamese'), ('zz', 'Other')], max_length=2, null=True)),
                ('requires_platform', models.CharField(blank=True, max_length=255, null=True)),
                ('requires_machine', models.CharField(blank=True, max_length=255, null=True)),
                ('requires_ram', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('side', models.CharField(blank=True, max_length=255, null=True)),
                ('side_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor', models.CharField(blank=True, max_length=255, null=True)),
                ('image_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Meta Chunk',
                'verbose_name_plural': 'Meta Chunks',
            },
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['uploaded', 'readyToUpload', 'needsWork'], name='entry_upload_status_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['-modified_date'], name='entry_modified_date_idx'),
        ),
    ]
